### ISSUE TITLE
Cohorts have names

### ISSUE THREAD

**Issue by dearshrewdwit** [boolean-uk/team-dev-server#119]
## User Story
Needed for https://github.com/boolean-uk/team-dev-client/issues/191

## Tasks
- Update the schema with a new column and constraint
- generate a migration
- update the create cohort endpoint to accept the name
- Send back appropriate error message/success data

## Check List
**Before PR**
- [x] Have tested locally using ThunderClient/Postman/etc.
- [x] For any new APIs, have documented in the README.md
- [x] Have included and tested any required schema changes
- [x] Have handled all error cases (try/catch, checked user input, etc.)
- [x] Error messages are consistent with the rest of the code
- [x] Correct HTTP Response codes and verbs are used
- [x] Code confirms to the existing style and structure
- [x] No warnings or errors are reported when using the API
- [x] If modifying an existing API the client app  already uses, have verified locally the client app still works as expected with changes
- [x] If adding a new API, any developers working on the client have reviewed the request params and expected responses

**After PR Merge**
- [ ] Have verified the API works on the deployed build using ThunderClient/Postman/etc.
- [ ] Have verified any required schema updates have been applied cleanly
- [ ] If modifying an existing API the client app already uses, have verified the deployed client app still works as expected

**Comment by dearshrewdwit** [comment]
```
Applying migration `20220628162644_cohort_name_unique_added_to_cohort_model`
Error: P3018
A migration failed to apply. New migrations cannot be applied before the error is recovered from. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve
Migration name: 20220628162644_cohort_name_unique_added_to_cohort_model

ERROR: column "cohortName" contains null values
DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E23502), message: "column \"cohortName\" contains null values", detail: None, hint: None, position: None, where_: None, schema: Some("prisma"), table: Some("Cohort"), column: Some("cohortName"), datatype: None, constraint: None, file: Some("tablecmds.c"), line: Some(4614), routine: Some("ATRewriteTable") }
```

Current Cohort table contains these records
![Screenshot 2022-06-29 at 14 29 28](https://user-images.githubusercontent.com/13719921/176448407-e01bf3e8-c521-47f5-9eec-2be861ac71f7.png)
