### ISSUE TITLE
Update the schema to have Conversation and Messages. [1]

### ISSUE THREAD

**Issue by SeanRichhh** [boolean-uk/team-dev-server#168]
## User Story
User has many conversations
Conversation has many ConversationMembers
User has many ConversationMembers
Conversation has many messages.

## Tasks
A Conversation has an id, name, a user id, and timestamps. 
ConversationMember is the join table - this has a conversation id and a user id
A message has an id, a user ID, a conversation ID, content, timestamps

## Check List
**Before PR**
- [ ] Have tested locally using ThunderClient/Postman/etc.
- [ ] For any new APIs, have documented in the README.md
- [ ] Have included and tested any required schema changes
- [ ] Have handled all error cases (try/catch, checked user input, etc.)
- [ ] Error messages are consistent with the rest of the code
- [ ] Correct HTTP Response codes and verbs are used
- [ ] Code confirms to the existing style and structure
- [ ] No warnings or errors are reported when using the API
- [ ] If modifying an existing API the client app  already uses, have verified locally the client app still works as expected with changes
- [ ] If adding a new API, any developers working on the client have reviewed the request params and expected responses

**After PR Merge**
- [ ] Have verified the API works on the deployed build using ThunderClient/Postman/etc.
- [ ] Have verified any requ
![unknown](https://user-images.githubusercontent.com/99200516/177748534-34edccf7-b695-476b-a9b8-20c73196800b.png)
ired schema updates have been applied cleanly
- [ ] If modifying an existing API the client app already uses, have verified the deployed client app still works as expected

**Comment by dearshrewdwit** [comment]
Proposed schema LGTM
