### ISSUE TITLE
Set privacy settings on posts

### ISSUE THREAD

**Issue by TomBrockington** [boolean-uk/team-dev-server#261]
#67 As a user, so I can sleep at night, I want to be able to set privacy settings on my posts 

## Tasks
A user should be able to choose to make a post of theirs private. They can do this when creating a new post, or by changing the setting on an existing post
By default, posts should be public
When set to private, only themselves and any role with elevated privileges (teachers, devs, admins) should be able to see the post
The user should also have a setting in their account to mark all future posts they create to default to private or public

## Check List
- [x] Set up receiving update request from client side using a 'togglePrivate' route and function 
- [x] Find user by :id GET request using the userId attached to the post '/user/:id'
- [x] Find Post by :id  GET request /post/:id/ 
- [x] Toggle the isPrivate value from true to false  
- [x] Return 404 if post not found or user not found

**Comment by shahzadnaeem** [comment]
A bit more detail on the endpoints for this? GET, PUT etc
Are there already some roles that you are updating? Is that what the first Check List item is?
