### ISSUE TITLE
#69 As a user, so I can leave the course, I want to deactivate my account

### ISSUE THREAD

**Issue by hubertlemczak** [boolean-uk/team-dev-server#272]
### Tasks

- [ ] Add isActive (Boolean? @default(true)) to the `User` model
   - [ ] When a user deactivates their account isActive will be false
- [ ] Update `getAll` posts controller to not include deactivated account likes
- [ ] Create formatting function that will replace data to be sent to client with `[removed]` for deactivated accounts
   - [ ] If `req.user.role` is TEACHER or ADMIN then original data will be sent to client
   - [ ] If `req.user.role` is STUDENT then formatted data will be sent to client

**Comment by Auenc** [comment]
Looks good to me :)
