### ISSUE TITLE
#72 As a user, so I can remove mean comments, I want to be able to delete comments on my posts.

### ISSUE THREAD

**Issue by hubertlemczak** [boolean-uk/team-dev-server#273]
### Tasks

- [ ] Create `delete post/:postId/comment/:comentId` endpoint [API-Spec](https://hubertlemczak.github.io/team-dev-api/#/comment/deleteComment)
- [ ] Create `patch post/:postId/comment/:comentId` endpoint [API-Spec](https://hubertlemczak.github.io/team-dev-api/#/comment/editComment)
   - [ ] To edit a comment a user must be the author of the comment 
- [ ] Add `onDelete: Cascade` to `CommentLike` model
- [ ] To delete a comment one of the following checks must pass
   - [ ] Check if the user is the author of the comment
   - [ ] Check if the user is the author of the post the comment is linked to
   - [ ] Check is user role is `TEACHER` or `ADMIN`
