### ISSUE TITLE
Update user profile data

### ISSUE THREAD

**Issue by dearshrewdwit** [boolean-uk/team-dev-server#80]
## User Story
As a user, I want to be able to update the information in my profile, including my password.

## Tasks
Create a route and controller to handle patch requests.
Send back the correct error messages

## Check List
**Before PR**
- [ ] Have tested locally using ThunderClient/Postman/etc.
- [ ] For any new endpoints, have documented in the README.md
- [ ] Have included and tested any required schema changes
- [ ] Have handled all error cases (try/catch, checked user input, etc.)
- [ ] Error messages are consistent with the rest of the code
- [ ] Correct HTTP Response codes and verbs are used
- [ ] Code confirms to the existing style and structure
- [ ] No warnings or errors are reported when using the API
- [ ] If modifying an existing API the client app  already uses, have verified locally the client app still works as expected with changes
- [ ] If adding a new API, any developers working on the client have reviewed the request params and expected responses

**After PR Merge**
- [ ] Have verified the API works on the deployed build using ThunderClient/Postman/etc.
- [ ] Have verified any required schema updates have been applied cleanly
- [ ] If modifying an existing endpoint the client app already uses, have verified the deployed client app still works as expected

**Comment by sigristarisa** [comment]
Worked on the steps of how we could accomplish the task (see Notion).
Added codes in the Notion page that might be helpful as a reference.
[Notion: Server Update User Profile Data](https://www.notion.so/Update-user-profile-data-55cdd5688df544ee9c2d288698ef2a44)
